require "logger"

require "bender/game"
require "bender/coord"
require "bender/ship"
require "bender/board"
require "bender/line_finder"
require "bender/ship_sinker"
require "bender/strategies"
require "bender/strategies/miss_penalty"
require "bender/strategies/hit_bonus"
require "bender/strategies/line_endings"
